Adding the aorc_bmi to cfe/extern/forcing_code and deleting correspon…
NOAA-OWP/cfe pull request #78
Opened 2023-02-27 21:43 UTC by WanruWu-NOAA

This PR is for adding the aorc_bmi to cfe/extern/forcing_code and deleting corresponding src and include files in cfe/forcing_code. 

## Additions

1. Added the new file:   .gitmodules
2. Added the new folder/files:   extern/forcing_code/

- include/aorc.h
- include/aorc_tools.h
- include/bmi_aorc.h
- include/bmi.h
- src/aorc.c
- src/bmi_aorc.c

## Removals
1. Deleted corresponding include files:

- deleted:    forcing_code/include/aorc.h
- deleted:    forcing_code/include/aorc_tools.h
- deleted:    forcing_code/include/bmi_aorc.h

2. Deleted corresponding src files: 

- deleted:    forcing_code/src/aorc.c
- deleted:    forcing_code/src/bmi_aorc.c

## Changes

1. Corresponding file path modifications:

- modified:   CMakeLists.txt
- modified:   README.md
- modified:   src/main_cfe_aorc_pet.c
- modified:   src/main_cfe_aorc_pet_rz_aet.cxx
- modified:   src/main_pass_forcings.c

2. Reflecting the aorc.c update in the aorc_bmi repo:

- updated:   extern/forcing_code (updated src/aorc.c)

## Testing

```
  mkdir build
  cd build
  cmake .. -DFORCING=ON
  make
  cd ..
  ./run_cfe.sh FORCING
```
and
```
  mkdir build
  cd build
  cmake .. -DFORCINGPET=ON
  make
  cd ..
  ./run_cfe.sh FORCINGPET
```

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [x ] PR has an informative and human-readable title
- [x ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Target Environment support

- [ ] Windows
- [x ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

2023-03-07 17:24 UTC, ajkhattak requested changes

2023-03-07 17:24 UTC, ajkhattak commented on CMakeLists.txt
> +add_executable(${exe_name} ./src/main_pass_forcings.c ./src/cfe.c ./src/bmi_cfe.c ./src/giuh.c ./extern/forcing_code/src/aorc.c ./extern/forcing_code/src/bmi_aorc.c)
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on CMakeLists.txt
> +add_executable(${exe_name} ./src/main_cfe_aorc_pet.c ./src/cfe.c ./src/bmi_cfe.c ./src/giuh.c ./extern/forcing_code/src/aorc.c ./extern/forcing_code/src/bmi_aorc.c ./forcing_code/src/pet.c ./forcing_
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on README.md
> +1. `gcc -lm ./src/main_pass_forcings.c ./src/cfe.c ./src/bmi_cfe.c ./src/giuh.c ./extern/forcing_code/src/aorc.c ./extern/forcing_code/src/bmi_aorc.c  -o cfe_forcing`. This generates an executable ca
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on README.md
> +1. `gcc -lm ./src/main_cfe_aorc_pet.c ./forcing_code/src/pet.c ./forcing_code/src/bmi_pet.c ./src/cfe.c ./src/bmi_cfe.c ./src/giuh.c ./extern/forcing_code/src/aorc.c ./extern/forcing_code/src/bmi_aor
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on src/main_cfe_aorc_pet.c
> +#include "../extern/forcing_code/include/aorc.h"
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on src/main_cfe_aorc_pet_rz_aet.cxx
> +#include "../extern/forcing_code/include/aorc.h"
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on src/main_pass_forcings.c
> +#include "../extern/forcing_code/include/aorc.h"
same comment as above

2023-03-07 17:24 UTC, ajkhattak commented on README.md
> +1. `gcc -lm ./src/main_pass_forcings.c ./src/cfe.c ./src/bmi_cfe.c ./src/giuh.c ./extern/forcing_code/src/aorc.c ./extern/forcing_code/src/bmi_aorc.c  -o cfe_forcing`. This generates an executable ca
In the `Compiling/Running section` please provide `git submodule update --init` for the user to pull the submodules before building the code.

2023-03-07 17:24 UTC, ajkhattak commented on src/main_cfe_aorc_pet.c
> +#include "../extern/forcing_code/include/bmi_aorc.h"
you also need to update your bmi_aorc.c. The existing aorc_bmi.c file in your repo is outdated as it expects rain in units of mm/sec while our forcing data is in mm/hr which leads to unexpected results. So please update your aorc_bmi.c file by copying cfe/forcing_code/src/bmi_aorc.c to your aorc_bmi repo.

2023-03-07 17:27 UTC, ajkhattak commented
@WanruWu-NOAA the PR looks good, just make sure to update your aorc_bmi.c and extern/forcing_code to extern/aorc_bmi to make the submodules' names consistent with other OWP repos.

2023-03-07 17:28 UTC, ajkhattak commented
and as always, let me know if you need my help.

2023-03-07 18:05 UTC, WanruWu-NOAA commented
@ajkhattak Thanks for the review and the recommendation for the submodule name change. I was following Keith's instruction on this and let's double check with him before I take any action. Or perhaps we can proceed this PR as is and change the name later to avoid any confusion? @SnowHydrology Please see Ahmad's recommendation on the submodule name change for cfe/extern/forcing_code and advise how we should proceed? Thanks, Wanru

2023-03-07 19:20 UTC, WanruWu-NOAA commented
We'll update bmi_aorc.c on aorc_bmi repo.

2023-03-07 22:58 UTC, WanruWu-NOAA commented
@ajkhattak @SnowHydrology I've just submitted a PR for updating bmi_aorc.c on the aorc_bmi repo after I tested this change with current PR and PR#79 - they both worked fine with path modification from  `#include "../../include/bmi.h"` to `#include "../include/bmi.h"`

2023-04-18 14:23 UTC, WanruWu-NOAA commented
@ajkhattak I have tested the modifications with the CFE standalone option "FORCING" and the `./run_cfe.sh FORCING` works correctly.

2023-04-20 19:45 UTC, WanruWu-NOAA commented
@ajkhattak Ahmad -- thanks Ahmad for merging the two branches/PRs and helping with the tests on my machine. The results look good for both` ./run_cfe.sh FORCING and ./run_cfe.sh FORCINGPET`.

2023-04-20 19:48 UTC, ajkhattak approved these changes
This is all set. Note: I have cherry-picked your changes from the wwu-dev2 PR, so don't need to merge that.

2023-04-20 19:49 UTC, merged